#!/usr/bin/env bash
set -eo pipefail
[[ $DOKKU_TRACE ]] && set -x

AUDIT_SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
AUDIT_PLUGIN_ROOT="$(cd "$AUDIT_SCRIPT_DIR/.." && pwd)"

exec "$AUDIT_PLUGIN_ROOT/subcommands/status" "$@"
